name: ✨ Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the use case it enables.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Possible Implementation
      description: If you have ideas on how this could be implemented, share them here.
    validations:
      required: false
